apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/ysubrama-tenant/devfile-sample/devfile-sample@sha256:ff6a1ae18f46e44aae13b74a0c9a7650cedb02e327b1c8b2acd34cdd09959dae
        name: my-nodejs
        resources: {}
status: {}
